services:
  - type: web
    name: fruit-predict-api
    env: python
    buildCommand: ""
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
